### ISSUE TITLE
FNC_casualtyCount and fnc_countTeam only counts editor-placed units.

### ISSUE THREAD

**Issue by gibfender** [dklollol/Olsen-Framework-Arma-3#116]
This is especially noticeable one the endscreen with the Casualty counts. Any units spawned after the game starts do not count towards the casualty count.

To reproduce: 

1. Create mission with 1 BLU player, 2 editor placed OPFOR AI and a radio trigger that spawns 2 more OPFOR AI. 
2. Use FNC_AddTeam and FNC_CasualtyPercentage to make the mission end when all OPFOR are dead 
3. Play the mission, killing all 4 opfor
4. Observe endscreen only showing 2 out of 2 opfor casualties.

**Comment by dklollol** [comment]
As far as i remember, there is no event handler for when units spawn, allowing us to easily automate it. So you have to manually tell the framework each time you spawn or remove a unit. But its not impossible to make a system detecting unit creating and deletion but it would be heavier CPU wise then the mission maker himself telling when he spawns and removes.

**Comment by gibfender** [comment]
Which function should be called when spawning a unit to add it to the team total?

**Comment by perfk** [comment]
_this call FNC_TrackUnit;

https://github.com/dklollol/Olsen-Framework-Arma-3/blob/master/core/functions/fnc_trackUnit.sqf

**Comment by gibfender** [comment]
Just wanted to say that **perfk**'s workaround works beautifully. Thanks!

**Comment by dklollol** [comment]
Just had a little giggle about this "cool new radical" "workaround" since its been around since 15 June 2016.
It has always been the intended way to do it, as i explained on 23 Nov 2016 it would be too heavy to automate it without unintended errors and performance issues.
Therefore people should manually add dynamically spawned units to be tracked.
Check the author of "fnc_trackUnit.sqf" btw :P.

And yeah i must admit the internal functions never had any good discover-ability ;)

https://github.com/dklollol/Olsen-Framework-Arma-3/commit/119d9821cf2883bd2ebb34c6483750de230496e0
