### ISSUE TITLE
Facewear not being added to units created post-init

### ISSUE THREAD

**Issue by luiz-silveira** [dklollol/Olsen-Framework-Arma-3#93]
Asked by Blackhawk to open this issue.

I've created a group using:

`	_group = createGroup EAST;
	_pos = doesntmatter;

	{
	 "O_Soldier_F" createUnit [_pos, _group, format ["[this, %1] call FNC_GearScript", str _x]];

	sleep 0.5;
	} foreach ["ISIS_TL", "ISIS_RFAT", "ISIS_AR", `"ISIS_RF"];`

All the gear is there, except for the headgear (balaclava). The balaclava is defined in #uniform between the uniform and the vest; both uniform and vest get added fine.

No script errors.

Mission is CO18_WAI1_The_First_Stance_v2.Takistan.pbo, on /FINAL.

**Comment by BlackHawkPL** [comment]
Engine assigns identity to unit a few frames after it's created, but for some reason in scheduled (reads config or does other engine stuff). Since gearscript runs in unscheduled, it adds gear before identity is set so balaclava is overwritten. Try using something like this: `format ["[this, %1] spawn {sleep 1; _this call FNC_GearScript}", str _x]`

**Comment by luiz-silveira** [comment]
Will do. But since this potentially happens with all facewear, wouldn't it be better to have it built into the gearscript? Every time the type of item is facewear, use the spawn/sleep routine to make sure it's added.
